### PR TITLE
Minor adjustments

### PR DESCRIPTION
**Pull request by hroncok**
I needed to do some adjustment to the code in order to be bale to run it on my computer (for example to avoid `/home/lbalhar/Dropbox/Projekty`). I hope it still works on your computer.

This:

 - runs on koji repo instead of rawhide compose
 - makes a difference between BR only and runtime deps in the report
 - caches `structure` for easier hacking
 - scps the report to fedorapeople as well
 - sorts source rpms for one packager by name
 - sort subpackages of one package by name, but shows the main package depchain first

### CODE REVIEW

**Comment by hroncok** [comment]
Results: https://churchyard.fedorapeople.org/report.txt

cc @encukou

**Comment by frenzymadness** [comment]
Notebook reviewed visually and it looks good to me.

**Comment by encukou** [comment]
That output looks great!

**Comment by frenzymadness** [comment]
Merge this!

**Comment by hroncok** [comment]
I cannot ;)

**Comment by encukou** [comment]
It's your repo, man

**Comment by frenzymadness** [comment]
:man_facepalming:

**Pull request merged**
